name: Build Status

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
   group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
   cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'setup.py'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: js/yarn.lock

    - name: Install yarn
      run: npm install -g yarn

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine jupyter_packaging
        python -m pip install -e .[dev]
        cd js; yarn

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        make tests
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Twine check
      run: |
        make dist

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: python_junit.xml
      if: ${{ always() }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: python_junit.xml
      if: ${{ matrix.os == 'ubuntu-latest' }}

    - name: Upload coverage
      uses: codecov/codecov-action@v3
